name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  UseMultiToolTask: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        platform: [Win32]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: microsoft/setup-msbuild@v1
    - uses: Trass3r/setup-cpp@master
    - name: Build
      run: msbuild /m /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} dxwrapper.sln
    - name: Upload DX7 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx7 game binaries
        path: bin/${{ matrix.config }}/dx7/*
    - name: Upload DX8 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx8 game binaries
        path: bin/${{ matrix.config }}/dx8/*
    - name: Upload DX9 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx9 game binaries
        path: bin/${{ matrix.config }}/dx9/*
    - name: Upload Matrix Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config }} binaries
        path: bin/${{ matrix.config }}/*
